### ISSUE TITLE
Segfault on resizing nodebox

### ISSUE THREAD

**Issue by rubenwardy** [rubenwardy/NodeBoxEditor#79]
```
    Program received signal SIGABRT, Aborted.
    0x00007ffff67ad267 in __GI_raise (sig=sig@entry=6)
        at ../sysdeps/unix/sysv/linux/raise.c:55
    55   ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
    (gdb) bt full
    #0  0x00007ffff67ad267 in __GI_raise (sig=sig@entry=6)
        at ../sysdeps/unix/sysv/linux/raise.c:55
            resultvar = 0
            pid = 11653
            selftid = 11653
    #1  0x00007ffff67aeeca in __GI_abort () at abort.c:89
            save_stage = 2
            act = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0},
              sa_mask = {__val = {0 <repeats 16 times>}}, sa_flags = 0,
              sa_restorer = 0x0}
            sigs = {__val = {32, 0 <repeats 15 times>}}
    #2  0x00007ffff67f0c53 in __libc_message (do_abort=do_abort@entry=1,
        fmt=fmt@entry=0x7ffff69091a8 "*** Error in `%s': %s: 0x%s ***\n")
        at ../sysdeps/posix/libc_fatal.c:175
            ap = {{gp_offset = 40, fp_offset = 0,
                overflow_arg_area = 0x7fffffffd000,
                reg_save_area = 0x7fffffffcf90}}
            fd = 6
            on_2 = <optimized out>
            list = <optimized out>
            nlist = <optimized out>
            cp = <optimized out>
            written = <optimized out>
    ---Type <return> to continue, or q <return> to quit---
    #3  0x00007ffff67f67c7 in malloc_printerr (action=<optimized out>,
        str=0x7ffff69091f0 "corrupted double-linked list (not small)",
        ptr=<optimized out>) at malloc.c:4965
            buf = "0000000001067890"
            cp = <optimized out>
    #4  0x00007ffff67fae25 in _int_malloc (
        av=av@entry=0x7ffff6b3cc00 <main_arena>, bytes=bytes@entry=1056)
        at malloc.c:3694
            p = <optimized out>
            iters = <optimized out>
            nb = <optimized out>
            idx = <optimized out>
            bin = <optimized out>
            victim = 0x1067890
            size = 1344
            victim_index = <optimized out>
            remainder = <optimized out>
            remainder_size = 272
            block = <optimized out>
            bit = <optimized out>
            map = <optimized out>
            fwd = 0x7ffff6b3d098 <main_arena+1176>
            bck = <optimized out>
    ---Type <return> to continue, or q <return> to quit---
            errstr = 0x0
            __func__ = "_int_malloc"
    #5  0x00007ffff67fd0b5 in __libc_calloc (n=<optimized out>,
        elem_size=<optimized out>) at malloc.c:3213
            av = 0x7ffff6b3cc00 <main_arena>
            oldtop = 0x106af20
            p = <optimized out>
            bytes = 1056
            sz = 1056
            csz = <optimized out>
            oldtopsize = 61664
            mem = <optimized out>
            clearsize = <optimized out>
            nclears = <optimized out>
            d = <optimized out>
            hook = <optimized out>
            __func__ = "__libc_calloc"
    #6  0x00007ffff3826c72 in ?? () from /usr/lib/x86_64-linux-gnu/dri/r600_dri.so
    No symbol table info available.
    #7  0x00007ffff37c6d37 in ?? () from /usr/lib/x86_64-linux-gnu/dri/r600_dri.so
    No symbol table info available.
    #8  0x00000000006838a5 in irr::video::COGLCoreCacheHandler<irr::video::COpenGLDriver, irr::video::COpenGLTexture>::STextureCache::set (this=0xe88120, index=0,
    ---Type <return> to continue, or q <return> to quit---
        texture=0x1041f90) at COGLCoreCacheHandler.h:83
            prevTexture = 0x1038910
            status = false
            type = irr::video::EDT_OPENGL
    #9  0x000000000068ca0e in irr::video::COpenGLTexture::uploadTexture (
        this=0x1038910, newTexture=true, mipmapData=0x0, level=0)
        at COpenGLTexture.cpp:578
            image = 0x102d6a0
            cacheHandler = 0xe88110
            prevTexture = 0x1041f90
            oldInternalFormat = 6408
            filtering = 9729
            compressedDataSize = 0
            source = 0x1038b80
    #10 0x000000000068ad57 in irr::video::COpenGLTexture::COpenGLTexture (
        this=0x1038910, origImage=0x10342e0, name=..., mipmapData=0x0,
        driver=0xe86890, __in_chrg=<optimized out>, __vtt_parm=<optimized out>)
        at COpenGLTexture.cpp:76
    No locals.
    #11 0x0000000000679186 in irr::video::COpenGLDriver::createDeviceDependentTexture (this=0xe86890, surface=0x10342e0, name=..., mipmapData=0x0)
        at COpenGLDriver.cpp:2526
    No locals.
    ---Type <return> to continue, or q <return> to quit---
    #12 0x00000000006650d8 in irr::video::CNullDriver::addTexture (this=0xe86890,
        name=..., image=0x10342e0, mipmapData=0x0) at CNullDriver.cpp:579
            t = 0x665070 <irr::video::CNullDriver::addTexture(irr::core::string<char, irr::core::irrAllocator<char> > const&, irr::video::IImage*, void*)>
    #13 0x00000000005919fa in darken(irr::video::IVideoDriver*, irr::video::IImage*, float, char const*) ()
    No symbol table info available.
    #14 0x00000000005925dd in NodeBox::buildMesh(EditorState*, irr::core::vector3d<int>, irr::IrrlichtDevice*, Media::Image**, bool) ()
    No symbol table info available.
    #15 0x000000000058ef2f in Node::remesh(NodeBox*) ()
    No symbol table info available.
    #16 0x000000000059b074 in CDR::update(NBEditor*, bool, irr::core::rect<int>) ()
        at ../../include/SMaterial.h:265
    No symbol table info available.
    #17 0x000000000059a77b in NBEditor::viewportTick(EViewport, irr::video::IVideoDriver*, irr::core::rect<int>) () at ../../include/SMaterial.h:265
    No symbol table info available.
    #18 0x0000000000583505 in Editor::viewportTick(EViewport, irr::core::rect<int>, bool, bool) ()
    No symbol table info available.
    #19 0x000000000058074b in Editor::run(irr::IrrlichtDevice*, Configuration*, bool) ()
    ---Type <return> to continue, or q <return> to quit---
    No symbol table info available.
    #20 0x00000000005783bd in main ()
    No symbol table info available.
```

**Comment by rubenwardy** [comment]
Reported by @DonBatman

**Comment by rubenwardy** [comment]
What commands did you run?

**Comment by DonBatman** [comment]
I just reinstalled my os and am in the process of setting everything up. I decided to try to compile this again. It compiled no problem and I can not find any issue using  it. It seems that there was a problem with my computer.

**Comment by rubenwardy** [comment]
I thought this would be the case. It's because of the use of the latest version of Irrlicht, which is buggy.
